language: python
cache: pip
dist: bionic

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint
  - jslint django_netjsonconfig/static/django-netjsonconfig/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - |
    openwisp-utils-qa-checks \
      --migration-path ./django_netjsonconfig/migrations/ \
      --migration-module django_netjsonconfig
  - coverage run --source=django_netjsonconfig runtests.py

after_success:
  coveralls
